name: Deploy to VPS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd frontend && npm ci
        cd ../backend && npm ci
        
    - name: Run tests
      run: |
        cd frontend && npm test -- --watchAll=false
        cd ../backend && npm test
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build
        
    - name: Deploy to VPS
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /opt/docker-platform
          git pull origin main
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          docker image prune -f
          echo "Deployment completed successfully!"
          
    - name: Health check
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        sleep 30
        curl -f https://${{ secrets.DOMAIN }}/health || exit 1 